name: bioinformatics
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.5.2
  - pip=22.3.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - appdirs==1.4.4
      - attrs==22.2.0
      - beautifulsoup4==4.11.2
      - bicon==1.3.4
      - bioservices==1.11.1
      - biothings-client==0.2.6
      - cattrs==22.2.0
      - charset-normalizer==3.0.1
      - colorama==0.4.6
      - colorlog==6.7.0
      - easydev==0.12.1
      - exceptiongroup==1.1.0
      - gevent==22.10.2
      - greenlet==2.0.2
      - grequests==0.6.0
      - gseapy==0.9.15
      - html5lib==1.1
      - idna==3.4
      - joblib==1.2.0
      - lxml==4.9.2
      - mygene==3.2.2
      - networkx==2.8.8
      - pyparsing==3.0.9
      - pytz==2022.7.1
      - requests==2.28.2
      - requests-cache==0.9.8
      - scikit-learn==1.2.1
      - soupsieve==2.3.2.post1
      - suds-community==1.1.2
      - threadpoolctl==3.1.0
      - tqdm==4.64.1
      - url-normalize==1.4.3
      - urllib3==1.26.14
      - webencodings==0.5.1
      - wrapt==1.14.1
      - xmltodict==0.13.0
      - zope-event==4.6
      - zope-interface==5.5.2
